#!/bin/sh

images=(
  'alpine' \
  'ubuntu' \
  'ruby'   \
  'debian' \
  'kalilinux/kali-linux-docker'
)

for image in "${images[@]}"; do
  echo "*** Pulling Docker Image: $image"
  /usr/local/bin/docker pull $image
done
